export const LAB_PARAMETERS = [
  "Leucocitos totales",
  "Neutrofilos %",
  "Linfocitos %",
  "Monocitos %",
  "Eosinofilos %",
  "Basofilos %",
  "Eritrocitos",
  "Hemoglobina",
  "Hematocrito",
  "Volumen corpuscular medio",
  "Hemoglobina corpuscular media",
  "CMHC",
  "RDW",
  "Plaquetas",
  "Volumen plaquetario medio",
  "Glucosa",
  "BUN",
  "Urea",
  "Creatinina serica",
  "Acido urico",
  "Albumina serica",
  "Colesterol total",
  "Trigliceridos",
  "HDL",
  "LDL",
  "Indice aterogenico",
  "Complemento C3",
  "Complemento C4",
  "Sodio serico",
  "Potasio serico",
  "Cloro serico",
  "Fosforo",
  "Magnesio",
  "Calcio",
  "Cistatina C",
  "Densidad urinaria",
  "pH urinario",
  "Proteinas en tira",
  "Glucosa urinaria",
  "Sangre urinaria",
  "Nitritos",
  "Esterasa leucocitaria",
  "Bacterias",
  "Celulas epiteliales",
  "Leucocitos urinarios",
  "Eritrocitos urinarios",
  "Cilindros",
  "Cristales",
  "Color urinario",
  "Aspecto urinario",
  "Sodio urinario",
  "Potasio urinario",
  "Cloro urinario",
  "Creatinina urinaria",
  "Microalbumina",
  "Albumina urinaria",
  "Relacion Albumina/Creatinina",
  "Insulina basal",
  "Vitamina D 25-OH"
]
